adagios/status/urls.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url, patterns

urlpatterns = patterns('adagios',
                        url(r'^/?$', 'status.views.status_index'),
                        url(r'^/acknowledgements/?$', 'status.views.acknowledgement_list'),
                        url(r'^/error/?$', 'status.views.error_page'),
                        url(r'^/comments/?$', 'status.views.comment_list'),
                        url(r'^/contacts/?$', 'status.views.contact_list'),
                        url(r'^/contactgroups/?$', 'status.views.contactgroups'),
                        url(r'^/dashboard/?$', 'status.views.dashboard'),
                        url(r'^/detail/?$', 'status.views.detail'),
                        url(r'^/downtimes/?$', 'status.views.downtime_list'),
                        url(r'^/hostgroups/?$', 'status.views.status_hostgroups'),
                        url(r'^/hosts/?$', 'status.views.hosts'),
                        url(r'^/log/?$', 'status.views.log'),
                        url(r'^/map/?', 'status.views.map_view'),
                        url(r'^/parents/?$', 'status.views.network_parents'),
                        url(r'^/perfdata/?$', 'status.views.perfdata'),
                        url(r'^/perfdata2/?$', 'status.views.perfdata2'),
                        url(r'^/problems/?$', 'status.views.problems'),
                        url(r'^/servicegroups/?$', 'status.views.status_servicegroups'),
                        url(r'^/services/?$', 'status.views.services'),
                        url(r'^/state_history/?$', 'status.views.state_history'),
                        url(r'^/backends/?$', 'status.views.backends'),



                        # Misc snippets
                        url(r'^/snippets/log/?$', 'status.views.snippets_log'),
                        url(r'^/snippets/services/?$', 'status.views.snippets_services'),
                        url(r'^/snippets/hosts/?$', 'status.views.snippets_hosts'),

                        # Misc tests
                        url(r'^/test/services/?$', 'status.views.services_js'),
                        url(r'^/test/status_dt/?$', 'status.views.status_dt'),
                        url(r'^/test/livestatus/?$', 'status.views.test_livestatus'),

                        # Deprecated as of 2013-03-23
                        url(r'^/contacts/(?P<contact_name>.+)/?$', 'status.views.contact_detail'),
                        url(r'^/hostgroups/(?P<hostgroup_name>.+)/?$', 'status.views.status_hostgroup'),
                        url(r'^/contactgroups/(?P<contactgroup_name>.+)/?$', 'status.views.contactgroup_detail'),
                        url(r'^/servicegroups/(?P<servicegroup_name>.+)/?$', 'status.views.servicegroup_detail'),
                        url(r'^/services_old/?$', 'status.views.status'),


                        )

adagios/urls.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url, patterns, include
from adagios import settings
from django.views.static import serve

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',
    # Example:
    url(r'^$', 'adagios.views.index', name="home"),
    url(r'^403', 'adagios.views.http_403'),
    url(r'^objectbrowser', include('adagios.objectbrowser.urls')),
    url(r'^status', include('adagios.status.urls')),
    url(r'^bi', include('adagios.bi.urls')),
    url(r'^misc', include('adagios.misc.urls')),
    url(r'^pnp', include('adagios.pnp.urls')),
    url(r'^media(?P<path>.*)$',         serve, {'document_root': settings.STATIC_ROOT }),
    url(r'^rest', include('adagios.rest.urls')),
    url(r'^contrib', include('adagios.contrib.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),

    # Internationalization
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}, name="media"),
    )
        

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#urlpatterns += staticfiles_urlpatterns()

adagios/status/forms.py
# -*- coding: utf-8 -*-
#
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2010, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.utils.translation import ugettext as _
import adagios.status.utils
import adagios.businessprocess


class LiveStatusForm(forms.Form):

    """ This form is used to generate a mk_livestatus query """
    table = forms.ChoiceField()
    columns = forms.MultipleChoiceField()
    filter1 = forms.ChoiceField(required=False)
    filter2 = forms.ChoiceField(required=False)


class RemoveSubProcessForm(forms.Form):

    """ Remove one specific sub process from a business process
    """
    process_name = forms.CharField(max_length=100, required=True)
    process_type = forms.CharField(max_length=100, required=True)

    def __init__(self, instance, *args, **kwargs):
        self.bp = instance
        super(RemoveSubProcessForm, self).__init__(*args, **kwargs)

    def save(self):
        process_name = self.cleaned_data.get('process_name')
        process_type = self.cleaned_data.get('process_type')
        self.bp.remove_process(process_name, process_type)
        self.bp.save()

status_method_choices = [(x, x) for x in adagios.businessprocess.BusinessProcess.status_calculation_methods]


class BusinessProcessForm(forms.Form):

    """ Use this form to edit a BusinessProcess """
    name = forms.CharField(max_length=100, required=True,
                           help_text=_("Unique name for this business process."))
    #processes = forms.CharField(max_length=100, required=False)
    display_name = forms.CharField(max_length=100, required=False,
                                   help_text=_("This is the name that will be displayed to users on this process. Usually it is the name of the system this business group represents."))
    notes = forms.CharField(max_length=1000, required=False,
                            help_text=_("Here you can put in any description of the business process you are adding. Its a good idea to write down what the business process is about and who to contact in case of downtimes."))
    status_method = forms.ChoiceField(
        choices=status_method_choices, help_text=_("Here you can choose which method is used to calculate the global status of this business process"))
    state_0 = forms.CharField(max_length=100, required=False,
                              help_text=_("Human friendly text for this respective state. You can type whatever you want but nagios style exit codes indicate that 0 should be 'ok'"))
    state_1 = forms.CharField(max_length=100, required=False,
                              help_text=_("Typically used to represent warning or performance problems"))
    state_2 = forms.CharField(max_length=100, required=False,
                              help_text=_("Typically used to represent critical status"))
    state_3 = forms.CharField(
        max_length=100, required=False, help_text=_("Use this when status is unknown"))
    #graphs = models.ManyToManyField(BusinessProcess, unique=False, blank=True)
    #graphs = models.ManyToManyField(BusinessProcess, unique=False, blank=True)

    def __init__(self, instance, *args, **kwargs):
        self.bp = instance
        super(BusinessProcessForm, self).__init__(*args, **kwargs)

    def save(self):
        c = self.cleaned_data
        self.bp.data.update(c)
        self.bp.save()

    def remove(self):
        c = self.data
        process_name = c.get('process_name')
        process_type = c.get('process_type')
        if process_type == 'None':
            process_type = None
        self.bp.remove_process(process_name, process_type)
        self.bp.save()

    def clean(self):
        cleaned_data = super(BusinessProcessForm, self).clean()

        # If name has changed, look if there is another business process with
        # same name.
        new_name = cleaned_data.get('name')
        if new_name and new_name != self.bp.name:
            if new_name in adagios.businessprocess.get_all_process_names():
                raise forms.ValidationError(
                    _("Cannot rename process to %s. Another process with that name already exists") % new_name
                )
        return cleaned_data

    def delete(self):
        """ Delete this business process """
        self.bp.delete()

    def add_process(self):

        process_name = self.data.get('process_name')
        hostgroup_name = self.data.get('hostgroup_name')
        servicegroup_name = self.data.get('servicegroup_name')
        service_name = self.data.get('service_name')

        if process_name:
            self.bp.add_process(process_name, None)
        if hostgroup_name:
            self.bp.add_process(hostgroup_name, None)
        if servicegroup_name:
            self.bp.add_process(servicegroup_name, None)
        if service_name:
            self.bp.add_process(service_name, None)
        self.bp.save()

choices = 'businessprocess', 'hostgroup', 'servicegroup', 'service', 'host'
process_type_choices = [(x, x) for x in choices]


class AddSubProcess(forms.Form):
    process_type = forms.ChoiceField(choices=process_type_choices)
    process_name = forms.CharField(
        widget=forms.HiddenInput(attrs={'style': "width: 300px;"}), max_length=100)
    display_name = forms.CharField(max_length=100, required=False)
    tags = forms.CharField(
        max_length=100, required=False, initial="not critical")

    def __init__(self, instance, *args, **kwargs):
        self.bp = instance
        super(AddSubProcess, self).__init__(*args, **kwargs)

    def save(self):
        self.bp.add_process(**self.cleaned_data)
        self.bp.save()


class AddHostgroupForm(forms.Form):
    pass


class AddGraphForm(forms.Form):
    host_name = forms.CharField(max_length=100,)
    service_description = forms.CharField(max_length=100, required=False)
    metric_name = forms.CharField(max_length=100, required=True)
    notes = forms.CharField(max_length=100, required=False,
                            help_text=_("Put here a friendly description of the graph"))

    def __init__(self, instance, *args, **kwargs):
        self.bp = instance
        super(AddGraphForm, self).__init__(*args, **kwargs)

    def save(self):
        self.bp.add_pnp_graph(**self.cleaned_data)
        self.bp.save()

adagios/status/templates/status_comments.html
{% extends "base_status.html" %}

{% load i18n %}

{% block title %}{% trans "Comments" %}{% endblock %}
{% block smallheader %}{% endblock %}
{% block largeheader %}{% trans "Comments" %}{% endblock %}

{% block nav1 %}{{ block.super }}{% endblock %}
{% block nav2 %}<a href="{% url 'status.views.comment_list' %}">{% trans "Comments" %}</a>{% endblock %}

{% load adagiostags %}

{% block content %}
    <ul class="nav nav-tabs" id="objecttab">
        <li class="active"><a href="{% url 'adagios.status.views.comment_list' %}" >{% trans "Comments" %}</a></li>
        <li><a href="{% url 'adagios.status.views.downtime_list' %}">{% trans "Downtimes" %}</a></li>
        <li><a href="{% url 'adagios.status.views.acknowledgement_list' %}">{% trans "Acknowledgements" %}</a></li>
    </ul>
    <div class="tab-content">

        <div class="tab-pane active" id="comments">
            {% include "snippets/status_commentlist_snippet.html" %}
        </div>

    </div>

{% endblock %}

{% block view_buttons %}{% endblock %}
{% block action_buttons %}{% endblock %}

{% block footer %} {{ block.super }} {% endblock %}

adagios/status/templates/status_dt.html
{% extends "base_status.html" %}
{% load i18n %}

{% block title %}{% trans "Datatable status" %}{% endblock %}
{% block nav2 %}
{% endblock %}
{% block smallheader %}
{% endblock %}
{% block largeheader %}
    {% trans "Datatable status" %}
{% endblock %}

{% block content %}

<table id="status_dt">
  <thead>
    <tr>
      <th>{% trans "Host name" %}</th>
      <th>{% trans "Service" %}</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
{% endblock %}

{% block header %} {{ block.super }}
{% endblock %}

{% block footer %}
{{ block.super }}

<script>
$(document).ready(function() {
    $('#status_dt').dataTable( {
        "bProcessing": true,
        "bServerSide": true,

        "sAjaxSource": "/rest/status/json/services_dt"
    } );
} );
</script>

{% endblock %}

adagios/status/templates/status_hostgroup.html
{% extends "base_status.html" %}

{% load i18n %}

{% block title %}{% trans "Hostgroup" %} {{ hostgroup_name }}{% endblock %}
{% block nav2 %}<a href="{% url 'status.views.status_hostgroups' %}">{% trans "Hostgroups" %}</a> / {{ hostgroup_name }}{% endblock %}
{% block smallheader %}{% trans "hostgroup" %}{% endblock %}
{% block largeheader %}{{ hostgroup_name }}{% endblock %}

{% block content %}
    <ul class="nav nav-tabs" id="objecttab">
        <li class="active"><a href="#information" data-toggle="tab">{% trans "Information" %}</a></li>
        <li><a href="#child_hostgroups" data-toggle="tab" id="hostgroups_link">{% trans "Child Hostgroups" %} {% if hostgroups %}<span class="muted">({{ hostgroups|length }})</span>{% endif %}</a></li>
        <li><a href="#hosts" data-toggle="tab" id="hosts_link">{% trans "Hosts" %} {% if hosts %}<span class="muted">({{ hosts|length }})</span>{% endif %}</a></li>
        <li><a href="#services" data-toggle="tab" id="services_link">{% trans "Services" %} {% if services %}<span class="muted">({{ services|length }})</span>{% endif %}</a></li>
        <li><a href="#history" data-toggle="tab" id="history_link">{% trans "History" %}</a></li>
        <li><a href="#debug" data-toggle="tab">{% trans "Debug" %}</a></li>

    </ul>
    <div class="tab-content">

        <div class="tab-pane active" id="information">
            {% if my_hostgroup %}
                <table class="table">
                    <tr>
                        <td>{% trans "Hostgroup Name" %}</td>
                        <td>{{ my_hostgroup.name }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Alias" %}</td>
                        <td>{{ my_hostgroup.alias }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "External links" %}</td>
                        <td>
                            {% if my_hostgroup.action_url %}
                                <a href="{{ my_hostgroup.action_url }}">action url</a>
                            {% endif %}

                            {% if my_hostgroup.notes_url %}
                                <a href="{{ my_hostgroup.notes_url }}">notes_url</a>
                            {% endif %}

                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="id_notes">{% trans "Notes" %}</label>
                        </td>
                        <td><textarea id="id_notes" cols="100" rows=3 name="notes">{{ my_object.notes }}</textarea></td>
                    </tr>
                    <tr>
                        <td>{% trans "Parent Hostgroups" %}</td>
                        <td>
                            {% for i in my_hostgroup.parent_hostgroups %}
                                <a href="{% url 'status.views.detail' %}?hostgroup_name={{  i  }}">{{ i }}</a>,
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table class="table well table-condensed">
                                <thead>
                                <tr><td colspan=2>{% trans "Host Status" %}</td></tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><div class="circle state_0"> </div> {% trans "Hosts up:" %} </td>
                                    <td>{{ my_hostgroup.num_hosts_up }}</td>
                                </tr>
                                <tr>
                                    <td><div class="circle state_2"> </div> {% trans "Hosts down:" %} </td>
                                    <td>{{ my_hostgroup.num_hosts_down }}</td>
                                </tr>
                                <tr>
                                    <td><div class="circle state_3"> </div> {% trans "Hosts unreachable:" %} </td>
                                    <td>{{ my_hostgroup.num_hosts_unreach }}</td>
                                </tr>
                                <tr><td colspan=2>...</td></tr>

                                <tr>
                                    <th>{% trans "Total:" %}</th>
                                    <th>{{ my_hostgroup.num_hosts }}</th>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <table class="table well table-condensed">
                                <thead>
                                <tr><td colspan=2>{% trans "Service Status" %}</td></tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><div class="circle state_0"> </div> OK: </td>
                                    <td>{{ my_hostgroup.num_services_ok }}</td>
                                </tr>
                                <tr>
                                    <td><div class="circle state_1"> </div> Warning: </td>
                                    <td>{{ my_hostgroup.num_services_warn }}</td>
                                </tr>
                                <tr>
                                    <td><div class="circle state_2"> </div> Critical: </td>
                                    <td>{{ my_hostgroup.num_services_crit }}</td>
                                </tr>
                                <tr>
                                    <td><div class="circle state_3"> </div> Unknown: </td>
                                    <td>{{ my_hostgroup.num_services_unknown }}</td>
                                </tr>
                                <tr>
                                    <th>{% trans "Total:" %}</th>
                                    <th>{{ my_hostgroup.num_services }}</th>
                                </tr>
                                </tbody>
                            </table>

                        </td>
                    </tr>
                </table>
            {% else %}
                {% blocktrans %}No Information found for hostgroup {{ hostgroup_name }}. Are you sure it exists ?{% endblocktrans %}
            {% endif %}

        </div>

        <div class="tab-pane " id="child_hostgroups">
            {% blocktrans %}hostgroups that belong to {{ hostgroup_name }}{% endblocktrans %}
            {% include "snippets/status_hostgrouplist_snippet.html" %}

        </div>

        <div class="tab-pane " id="hosts">
            {% blocktrans %}Hosts that belong to {{ hostgroup_name }}{% endblocktrans %}
            <div id="hostlist">{% trans "This dialog should start loading when you click the hosts tab" %}</div>
        </div>

        <div class="tab-pane " id="services">
            {% blocktrans %}Services that belong to {{ hostgroup_name }}{% endblocktrans %}
            <div id="servicelist">{% trans "This dialog should start loading when you click the services tab" %}</div>
        </div>

        <div class="tab-pane" id="history">
            <div id="logdiv">
                {% trans "This dialog should reload when the history tab is clicked." %}
            </div>
        </div>
        <div class="tab-pane" id="debug">
            <h4>Information available via livestatus:</h4>
            <table class="table-condensed table">
                {% for k,v in my_hostgroup.items %}
                    <tr>
                        <td>                {{ k }}
                        </td>
                        <td>
                            {{ v }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <!-- has to be here for the action buttons to work -->
    <div  id="hostgroupstatus" class="hide">
        <table>
            <tbody>
            <tr>
                <td class="selectable">
                    <input class="chkbox chkbox-primary"  style="margin: -2px; padding: 0px;" type="checkbox" checked="checked" name="hostgroup" value="{{ hostgroup_name }}" data-hostgroup_name="{{ hostgroup_name }}" data-object_type="hostgroup">
                    <input type="hidden" class="input_hostname" name="host_name" value="{{ host_name }}">
                    <input type="hidden" class="input_service_description" name="service_description" value="{{ service_description }}">

                </td>
            </tr>
            </tbody>
        </table>
    </div>


{% endblock %}

{% block footer %}
    {{ block.super }}
    <style>
    .input-append button.add-on {
        height: inherit !important;
    }
        /* avoid bootstrap highlight */
    .table tbody tr:hover td, .table tbody tr:hover th {
        background-color: transparent;
    }
    </style>
    <script>
        // When history link is clicked, load the log history for this object
        $('#history_link').click(function(event) {
            // Load log history in its own tab
            $('#logdiv').html(gettext("Loading ..."));
            var hostgroup_name = encodeURIComponent("{{ hostgroup_name }}");
            var snippet_url = '{% url "adagios.status.views.snippets_log" %}?object_type=hostgroup&hostgroup_name=' + hostgroup_name;
            $('#logdiv').load(snippet_url);
        });

        $('#services_link').click(function(event) {
            // Load log history in its own tab
            $('#servicelist').html(gettext("Loading ..."));
            var hostgroup_name = encodeURIComponent("{{ hostgroup_name }}");
            var snippet_url = '{% url 'adagios.status.views.snippets_services' %}?host_groups__has_field=' + hostgroup_name;
            $('#servicelist').load(snippet_url, function() {
                adagios.status.initilize_multiselect_checkboxes();
            });
        });

        $('#hosts_link').click(function(event) {
            // Load log history in its own tab
            $('#hostlist').html(gettext("Loading ..."));
            var hostgroup_name = encodeURIComponent("{{ hostgroup_name }}");
            var snippet_url = '{% url 'adagios.status.views.snippets_hosts' %}?host_groups__has_field=' + hostgroup_name;
            $('#hostlist').load(snippet_url, function() {
                adagios.status.initilize_multiselect_checkboxes();
            });
        });

    </script>

{% endblock %}

adagios/status/templates/status_menubar.html
{% load i18n %}


<li class="{% if 'status' in urlname %}active{% endif %}">
  <a href="{% url 'status.views.status_index' %}"><i class="glyph-grey glyph-table"></i>{% trans " Status" %}</a>
</li>

adagios/status/templates/status_problems.html
{% extends "base_status.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Host And Service Overview" %}{% endblock %}
{% block smallheader %}{% endblock %}
{% block largeheader %}{% trans "Host And Service Overview" %}{% endblock %}
{% block nav1 %}{{ block.super }}{% endblock %}
{% block nav2 %}<a href="{% url "status.views.services" %}">{% trans "Services" %}</a>{% endblock %}
{% load adagiostags %}

{% block sidebar_outer %}
{% endblock %}


{% block content %}
    {% if hosts %}
        {% trans "Hosts:" %}
        {% include "snippets/status_hostlist_snippet.html" %}
    <hr>
    {% else %}
        <p>{% trans "There are no host problems." %}</p>
    {% endif %}
    {% if services %}
        {% trans "Services:" %}
        {% include "snippets/status_servicelist_snippet.html" %}
    {% else %}
        <p>{% trans "There are no service problems." %}</p>
    {% endif %}
{% endblock %}



{% block footer %}
    {{ block.super }}

    <script>
        // Set a reload in X seconds
        adagios.misc.timed_reload({{ user_data.refresh_rate }});
    </script>
{% endblock %}

adagios/status/templates/status_servicegroup.html
{% extends "base_status.html" %}
{% load i18n %}


{% block title %}Servicegroup Detail{% endblock %}
{% block smallheader %}{% endblock %}

{% block largeheader %}Servicegroup {{ servicegroup_name }}{% endblock %}

{% block content %}
    {% include "snippets/status_servicelist_snippet.html" %}
{% endblock %}



{% block view_buttons %}
<div class="btn-group pull-left" id="view_buttons">
    <a class="btn btn-small dropdown-toggle " data-toggle="dropdown" href="#">
        <i class="glyph-eye-open" title="View"> </i> <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="?servicegroup_name={{ servicegroup_name }}&unhandled"> Open Problems</a></li>
        <li><a href="?servicegroup_name={{ servicegroup_name }}&state__isnot=0"> All Problems</a></li>
        <li><a href="?servicegroup_name={{ servicegroup_name }}&acknowledged=1"> All Acknowledged</a></li>
        <li><a href="?servicegroup_name={{ servicegroup_name }}&scheduled_downtime_depth__isnot=0"> All in Downtime</a></li>
        <li><a href="?servicegroup_name={{ servicegroup_name }}&state=0"> All OK</a></li>
        <li><a href="?servicegroup_name={{ servicegroup_name }}"> Everything</a></li>
    </ul>
</div>
{% endblock %}

adagios/status/templates/status_servicegroups.html
{% extends "base_status.html" %}

{% load i18n %}

{% block title %}{% trans "Servicegroups" %}{% endblock %}

{% block nav2 %}
    <a href="{% url 'status.views.status_servicegroups' %}">{% trans "Servicegroups" %}</a>
{% endblock %}
{% block smallheader %}{% endblock %}

{% block largeheader %}{% trans "Servicegroups" %}{% endblock %}

{% block content %}
    {% include "snippets/status_servicegrouplist_snippet.html" %}
{% endblock %}



{% block view_buttons %}{% endblock %}
{% block action_buttons %}{% endblock %}

adagios/status/templates/status_services.html
{% extends "base_status.html" %}

{% load i18n %}

{% block title %}{% trans "Status Overview" %}{% endblock %}
{% block smallheader %}{% endblock %}
{% block largeheader %}{% trans "Service Overview" %}{% endblock %}
{% block nav1 %}{{ block.super }}{% endblock %}
{% block nav2 %}<a href="{% url 'status.views.services' %}">{% trans "Services" %}</a>{% endblock %}
{% load adagiostags %}

{% block sidebar_outer %}
{% endblock %}

{% block content %}
    {% include "snippets/status_servicelist_snippet.html" %}
{% endblock %}



{% block footer %}
    {{ block.super }}

    <script>
        // Set a reload in X seconds
        adagios.misc.timed_reload({{ user_data.refresh_rate }});
    </script>
{% endblock %}