adagios/okconfig_/urls.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url, patterns

urlpatterns = patterns('adagios',

                      url(r'^/scan_network/?', 'okconfig_.views.scan_network'),
                      url(r'^/addgroup/?', 'okconfig_.views.addgroup'),
                      url(r'^/addtemplate/?', 'okconfig_.views.addtemplate'),
                      url(r'^/addhost/?', 'okconfig_.views.addhost'),
                      url(r'^/addservice/?', 'okconfig_.views.addservice'),
                      url(r'^/install_agent/?', 'okconfig_.views.install_agent'),
                      url(r'^/edit/?$', 'okconfig_.views.choose_host'),
                      url(r'^/edit/(?P<host_name>.+)$', 'okconfig_.views.edit'),
                      url(r'^/verify_okconfig/?',
                       'okconfig_.views.verify_okconfig'),
                      )

adagios/urls.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url, patterns, include
from adagios import settings
from django.views.static import serve

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',
    # Example:
    url(r'^$', 'adagios.views.index', name="home"),
    url(r'^403', 'adagios.views.http_403'),
    url(r'^objectbrowser', include('adagios.objectbrowser.urls')),
    url(r'^status', include('adagios.status.urls')),
    url(r'^bi', include('adagios.bi.urls')),
    url(r'^misc', include('adagios.misc.urls')),
    url(r'^pnp', include('adagios.pnp.urls')),
    url(r'^media(?P<path>.*)$',         serve, {'document_root': settings.STATIC_ROOT }),
    url(r'^rest', include('adagios.rest.urls')),
    url(r'^contrib', include('adagios.contrib.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),

    # Internationalization
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}, name="media"),
    )
        

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#urlpatterns += staticfiles_urlpatterns()

adagios/okconfig_/models.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models

# Create your models here.

adagios/okconfig_/forms.py
# Adagios is a web based Nagios configuration interface
#
# Copyright (C) 2014, Pall Sigurdsson <palli@opensource.is>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
import okconfig
from adagios.misc import helpers
import re
from django.core.exceptions import ValidationError
import socket
from pynag import Model
from adagios.forms import AdagiosForm
from django.utils.translation import ugettext as _


def get_all_hosts():
    return [('', _('Select a host'))] + [(x, x) for x in helpers.get_host_names()]


def get_all_templates():
    all_templates = okconfig.get_templates()
    service_templates = [x for x in all_templates if 'host' not in x]
    return [(x, _("Standard %(service_template)s checks") % {"service_template": x}) for x in service_templates]


def get_all_groups():
    return [(x, x) for x in okconfig.get_groups()]


def get_inactive_services():
    """ List of all unregistered services (templates) """
    inactive_services = [('', _('Select a service'))]
    inactive_services += [(x.name, x.name) for x in Model.Service.objects.filter(service_description__contains="", name__contains="", register="0")]
    inactive_services.sort()
    return inactive_services


class ScanNetworkForm(AdagiosForm):
    network_address = forms.CharField()

    def clean_network_address(self):
        addr = self.cleaned_data['network_address']
        if addr.find('/') > -1:
            addr, mask = addr.split('/', 1)
            if not mask.isdigit():
                raise ValidationError(_("not a valid netmask"))
            if not self.isValidIPAddress(addr):
                raise ValidationError(_("not a valid ip address"))
        else:
            if not self.isValidIPAddress(addr):
                raise ValidationError(_("not a valid ip address"))
        return self.cleaned_data['network_address']

    def isValidHostname(self, hostname):
        if len(hostname) > 255:
            return False
        if hostname[-1:] == ".":
            # strip exactly one dot from the right, if present
            hostname = hostname[:-1]
        allowed = re.compile("(?!-)[A-Z\d-]{1,63}(?<!-)$", re.IGNORECASE)
        for x in hostname.split("."):
            if allowed.match(x) is False:
                return False
        return True

    def isValidIPAddress(self, ipaddress):
        try:
            socket.inet_aton(ipaddress)
        except Exception:
            return False
        return True


class AddGroupForm(AdagiosForm):
    group_name = forms.CharField(help_text=_("Example: databases"))
    alias = forms.CharField(help_text=_("Human friendly name for the group"))
    force = forms.BooleanField(
        required=False, help_text=_("Overwrite group if it already exists."))


class AddHostForm(AdagiosForm):
    host_name = forms.CharField(help_text=_("Name of the host to add"))
    address = forms.CharField(help_text=_("IP Address of this host"))
    group_name = forms.ChoiceField(
        initial="default", help_text=_("host/contact group to put this host in"))
    templates = forms.MultipleChoiceField(
        required=False, help_text=_("Add standard template of checks to this host"))
    force = forms.BooleanField(
        required=False, help_text=_("Overwrite host if it already exists."))

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['group_name'].choices = choices = get_all_groups()
        self.fields['templates'].choices = get_all_templates()

    def clean(self):
        cleaned_data = super(AddHostForm, self).clean()
        force = self.cleaned_data.get('force')
        host_name = self.cleaned_data.get('host_name')
        templates = self.cleaned_data.get('templates')
        for i in templates:
            if i not in list(okconfig.get_templates().keys()):
                self._errors['templates'] = self.error_class(
                    [_('template %s was not found') % i])
        if not force and host_name in okconfig.get_hosts():
            self._errors['host_name'] = self.error_class(
                [_('Host name already exists. Use force to overwrite')])
        return cleaned_data


class AddTemplateForm(AdagiosForm):
    # Attributes
    host_name = forms.ChoiceField(help_text=_("Add templates to this host"))
    templates = forms.MultipleChoiceField(
        required=False, help_text=_("Add standard template of checks to this host"))
    force = forms.BooleanField(
        required=False, help_text=_("Overwrites templates if they already exist"))

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['templates'].choices = get_all_templates()
        self.fields['host_name'].choices = get_all_hosts()

    def clean(self):
        cleaned_data = super(AddTemplateForm, self).clean()
        force = self.cleaned_data.get('force')
        host_name = self.cleaned_data.get('host_name')
        templates = self.cleaned_data.get('templates')
        for i in templates:
            if i not in list(okconfig.get_templates().keys()):
                self._errors['templates'] = self.error_class(
                    [_('template %s was not found') % i])
        if not force and host_name not in okconfig.get_hosts():
            self._errors['host_name'] = self.error_class(
                [_('Host name not found Use force to write template anyway')])
        return cleaned_data

    def save(self):
        host_name = self.cleaned_data['host_name']
        templates = self.cleaned_data['templates']
        force = self.cleaned_data['force']
        self.filelist = []
        for i in templates:
            self.filelist += okconfig.addtemplate(
                host_name=host_name, template_name=i, force=force)


class InstallAgentForm(AdagiosForm):
    remote_host = forms.CharField(help_text=_("Host or ip address"))
    install_method = forms.ChoiceField(
        initial='ssh', help_text=_("Make sure firewalls are not blocking ports 22(for ssh) or 445(for winexe)"),
        choices=[(_('auto detect'), _('auto detect')), ('ssh', 'ssh'), ('winexe', 'winexe')])
    username = forms.CharField(
        initial='root', help_text=_("Log into remote machine with as this user"))
    password = forms.CharField(
        required=False, widget=forms.PasswordInput, help_text=_("Leave empty if using kerberos or ssh keys"))
    windows_domain = forms.CharField(
        required=False, help_text=_("If remote machine is running a windows domain"))


class ChooseHostForm(AdagiosForm):
    host_name = forms.ChoiceField(help_text=_("Select which host to edit"))

    def __init__(self, service=Model.Service(), *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        self.fields['host_name'].choices = get_all_hosts()


class AddServiceToHostForm(AdagiosForm):
    host_name = forms.ChoiceField(
        help_text=_("Select host which you want to add service check to"))
    service = forms.ChoiceField(
        help_text=_("Select which service check you want to add to this host"))

    def __init__(self, service=Model.Service(), *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        self.fields['host_name'].choices = get_all_hosts()
        self.fields['service'].choices = get_inactive_services()


class EditTemplateForm(AdagiosForm):

    def __init__(self, service=Model.Service(), *args, **kwargs):
        self.service = service
        super(forms.Form, self).__init__(*args, **kwargs)

        # Run through all the all attributes. Add
        # to form everything that starts with "_"
        self.description = service['service_description']
        fieldname = "%s::%s::%s" % (
            service['host_name'], service['service_description'], 'register')
        self.fields[fieldname] = forms.BooleanField(
            required=False, initial=service['register'] == "1", label='register')
        self.register = fieldname

        macros = []
        self.command_line = None
        try:
            self.command_line = service.get_effective_command_line()
            for macro, value in list(service.get_all_macros().items()):
                if macro.startswith('$_SERVICE') or macro.startswith('S$ARG'):
                    macros.append(macro)
            for k in sorted(macros):
                fieldname = "%s::%s::%s" % (
                    service['host_name'], service['service_description'], k)
                label = k.replace('$_SERVICE', '')
                label = label.replace('_', ' ')
                label = label.replace('$', '')
                label = label.capitalize()
                self.fields[fieldname] = forms.CharField(
                    required=False, initial=service.get_macro(k), label=label)
        # KeyError can occur if service has an invalid check_command
        except KeyError:
            pass

    def save(self):
        for i in self.changed_data:
            # Changed data comes in the format host_name::service_description::$_SERVICE_PING
            # We need to change that to just __PING
            field_name = i.split('::')[2]
            field_name = field_name.replace('$_SERVICE', '_')
            field_name = field_name.replace('$', '')
            data = self.cleaned_data[i]
            if field_name == 'register':
                data = int(data)

adagios/okconfig_/templates/addcomplete.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Add Complete" %}{% endblock %}
{% block smallheader %}{% trans "Add" %}{% endblock %}
{% block largeheader %}{% trans "Complete" %}{% endblock %}
{% block toolbar %}{% endblock %}
{%  block content %}
{% trans "Next Steps:" %}

<ul>
    {% if host_name %}
        <li><a href="{% url "okconfig_.views.install_agent" %}?remote_host={{ host_name }}">Install an agent</a> {% blocktrans %}on host {{host_name}}{% endblocktrans %}</li>
        <li><a href="{% url "adagios.objectbrowser.views.edit_object" %}?object_type=host&host_name={{ host_name }}">Configure</a> {% blocktrans %}host {{host_name}} {% endblocktrans %}</li>
        <li><a href="{% url "okconfig_.views.edit" host_name=host_name %}">{% blocktrans %}Edit the services</a> on host {{host_name}} {% endblocktrans %}</li>
        <li><a href="{% url "okconfig_.views.addtemplate" %}?host_name={{host_name}}">{% blocktrans %}Add service checks</a> to {{host_name}}{% endblocktrans %}</li>
    {% endif %}

    {% if group_name %}
     <li><a href="{% url "okconfig_.views.addhost" %}?group_name={{group_name}}">{% blocktrans %}Add Hosts to {{group_name}}{% endblocktrans %}</a></li>
    {% endif %}

    <li><a href="{% url "adagios.misc.views.nagios_service" %}">{% trans "Reload Nagios" %}</a>{% trans "to apply your changes" %}</li>
</ul>
<ul>
    {% if filelist %}
      {% for file in filelist %}
       <li>{% trans "See what was written to" %} <a href="{% url "objectbrowser.views.search_objects" %}?filename={{file}}">{{file}}</a></li>
      {% endfor %}
    {% endif %}

</ul>

{% endblock %}

adagios/okconfig_/templates/addgroup.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Add Group" %}{% endblock %}
{% block smallheader %}{% trans "Add" %}{% endblock %}
{% block largeheader %}{% trans "Group" %}{% endblock %}
{% block toolbar %}{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.addgroup" %}">{% trans "Add Group" %}</a>{% endblock %}


{% block content %}
    <form action="#" method="post" class="form-horizontal">{% csrf_token %}
        {% include "bootstrap_fields.html" with fields=form %}
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </div>
    </form>
{% endblock %}

adagios/okconfig_/templates/addhost.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Add Host" %}{% endblock %}
{% block smallheader %}{% trans "Add" %}{% endblock %}
{% block largeheader %}{% trans "Host" %}{% endblock %}
{% block toolbar %}{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.addhost" %}">{% trans "Add Host" %}</a>{% endblock %}

{% block content %}
    <br/>
	<form action="#" method="post" class="form-horizontal">{% csrf_token %}
        {% include "bootstrap_fields.html" with fields=form %}
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </div>
	</form>
{% endblock %}



{% block footer %}
    {{ block.super }}
    <!-- DNS lookup for the address field -->
    <script>
        $('#id_host_name').focusout(function() {
            if ($('#id_address').val() == "") {
                var parameters = {};
                parameters['host_name'] = $(this).val();
                adagios.rest.pynag.dnslookup(parameters)
                        .done( function(data) {
                            $('#id_address').val(data['addresslist'][0]);
                        }
                );
            }
        });
    </script>

{% endblock %}

adagios/okconfig_/templates/addservice.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Add Service" %}{% endblock %}
{% block smallheader %}{% trans "add" %} {% endblock %}
{% block largeheader %}{% trans "service" %} {% endblock %}
{% block toolbar %}{% endblock %}
{% block header %}
{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.addservice" %}">{% trans "Add Service" %}</a>{% endblock %}

{% block content %}

                {% if form %}


                    <form action="#" id="add_service_to_host" method="POST" class="form-horizontal">{% csrf_token %}
                        <fieldset>
                            <legend>{% trans "Select host name and service" %}</legend>
                            {% for field in form %}
                                <label class="control-label" for="{{ field.name }}">{{ field.label }}{% if field.help %} <abbr rel="tooltip" title="{{ field.label }}" data-content="{{ field.help_text }}"><i class="icon-question-sign"></i></abbr> {% endif %}</label>
                                <div class="controls" id="advanced_field">
                                    {{ field }}
                                </div>

                            {% endfor %}
                        </fieldset>
                        <div id="service_macros" class="hide">
                            <fieldset>
                                <legend> <span id="service_name"></span></legend>
                                <span id="notes"><! -- notes will go in here --></span>
                                <span id="notes_url"><!-- notes_url will go here --></span>
                                <p></p>
                                <table class="table table-condensed">
                                    <tbody id="macros_for_this_service"><!-- Macros will go in here --></tbody>
                                </table>

                            </fieldset>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary" type="submit">{% trans "Add service" %}</button>
                        </div>
                    </form>
                {% endif %}


{% endblock %}

{% block footer %}

    <script>
    $('select#id_service').change(function() {
        var $this = $(this);
        $('#macros_for_this_service').html('');
        $("#notes_url").html('');
        $("#notes").html('');
        $('#service_macros').hide();
        $.getJSON(BASE_URL + "rest/pynag/json/get_objects",
                {
                    name: $(this).val(),
                    object_type: 'service',
                    with_fields: '*'
                },
                function (data) {
                    var num_fields = 0;
                    if (data[0]) {
                        var myservice = data[0];
                    } else {
                        console.log("Called get_objects but got empty results for " + $(this).val());
                    }
                    var myobj = data[0];
                    var service_macro_html = '';
                    console.log(myobj);
                    var friendly_name = null;
                    $.each(myobj, function(i, k) {
                        if (i.substring(0, 1) == "_" || i == 'service_description') {
                            num_fields += 1;
                            friendly_name = i.replace('$_SERVICE', '').replace('$','');

                            // replace all underscores with space:
                            friendly_name = friendly_name.split('_').join(' ');

                            service_macro_html += '<tr><td>' +
                                    friendly_name +
                                    '</td><td>' +
                                    '  <input type="text" class="span11" name="' + i + '" value="' + myobj[i] + '">' +
                                    '</td>';
                        }
                        if (i == 'notes') {
                            $("#notes").html(myobj[i]);
                        }
                        if (i == 'notes_url') {
                            $("#notes_url").html("See documentation <a href='" + myobj[i] + "'>here</a>." );
                        }
                    });
                    service_macro_html += "";
                    if (num_fields) {
                        $('#service_name').text($this.val());
                        $('#macros_for_this_service').html(service_macro_html);
                        $('#service_macros').show();
                    }
                }).error(function(jqXHR) {
                    console.log('Failed to fetch data: URL: "' + this.url + '" Server Status: "' + jqXHR.status + '" Status: "' + jqXHR.statusText + '"');
                });
    });
    </script>
{%  endblock %}

adagios/okconfig_/templates/addtemplate.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Add Template" %}{% endblock %}
{% block smallheader %}{% trans "Add" %}{% endblock %}
{% block largeheader %}{% trans "Template" %}{% endblock %}
{% block toolbar %}{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.addtemplate" %}">{% trans "Add Template" %}</a>{% endblock %}
{% block footer %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <form action="#" method="post" class="form-horizontal">{% csrf_token %}
        {% include "bootstrap_fields.html" with fields=form %}
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </div>
    </form>
    <div id="template_services">
    </div>
{% endblock %}

adagios/okconfig_/templates/choosehost.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Edit host" %}{% endblock %}
{% block smallheader %}{% trans "Edit" %}{% endblock %}
{% block largeheader %}{% trans "Host thresholds" %}{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.choose_host" %}">{% trans "Edit Host" %}</a>{% endblock %}
{% block toolbar %}{% endblock %}

{% block content %}
Please choose a host.
    <form action="#" method="post" class="form-horizontal">{% csrf_token %}
        {% include "bootstrap_fields.html" with fields=form %}
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
        </div>
    </form>

{% endblock %}

adagios/okconfig_/templates/install_agent.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Install Agent" %}${% endblock %}
{% block smallheader %}{% trans "Install" %}{% endblock %}
{% block largeheader %}{% trans "Agent" %}{% endblock %}
{% block nav2 %}<a href="{% url "adagios.okconfig_.views.install_agent" %}">{% trans "Install Agent" %}</a>{% endblock %}
{% block toolbar %}{% endblock %}
{% block footer %}
    <script>
    $(document).ready(function() {
        var windows_domain_div = $("label.control-label[for='windows_domain']").parent();
        var install_method = $("div#install_agent #id_install_method");
        if (install_method.val() == 'winexe') {
            windows_domain_div.show();
        } else {
            windows_domain_div.hide();
        }
        $("div#install_agent").show();
        install_method.on('change', function() {
            if ($(this).val() == 'winexe') {
                windows_domain_div.show();
                $('#id_username').val("administrator");
            } else {
                windows_domain_div.hide();
                $('#id_username').val("root");
            }
        });

        // Some error handling code. We look through value of stdout and depending on what output it gives,
        // we will display a user friendly error message.
        var stdout = $("#stdout").text();
        var stderr = $("#stderr").text();
        if (stdout.search("NT_STATUS_LOGON_FAILURE") >= 0) { $("#NT_STATUS_LOGON_FAILURE").show(); }
        if (stdout.search("NT_STATUS_DUPLICATE_NAME") >= 0) { $("#NT_STATUS_DUPLICATE_NAME").show(); }
        if (stdout.search("NT_STATUS_ACCESS_DENIED") >= 0) { $("#NT_STATUS_ACCESS_DENIED").show(); }
        if (stderr.search("Error: Directory") >= 0 && stderr.search("not found") >= 0 ) { $("#nsclient_missing").show(); }

    });
    </script>
{% endblock %}


{% block content %}

    {% if exit_status %}
        {% if exit_status == "0" %}
            <div class="alert alert-success">{% trans "Install Success." %} (exit status=0)</div>
        {% else %}
            <div class="alert alert-danger">{% trans "Install failed." %} (exit status={{ exit_status }})</div>
        {% endif %}
    {% endif %}

    <!-- Friendly error messages -->
    <div id="friendly_error_messages">
        <div id="NT_STATUS_LOGON_FAILURE" class=hide>
            <pre>{% trans "Could not log in to server. Make sure you are using correct username and password." %}</pre>
        </div>

        <div id="NT_STATUS_DUPLICATE_NAME" class=hide>
            <pre>
{% trans "The security settings on the remote windows host might forbid logins if the host name specified does not match the computername on the server." %}

{% trans "Try again with either correct hostname or the ip address of the server." %}</pre>
        </div>

        <div id="NT_STATUS_ACCESS_DENIED" class=hide>
            <pre>{% trans "Make sure that the user is a local administrator on the windows host." %}</pre>
        </div>

        <div id="nsclient_missing" class=hide>
                {% trans "Seems like there is no copy of nsclient installed on the remote server. Have you tried the following:" %}

                <pre>
# {% trans "Get nsclient 32-bit and 64-bit copies from opinkerfi github repo:" %}
cd /opt
git clone http://github.com/opinkerfi/misc

# {% trans "Copy nsclient to where okconfig expects it to live:" %}
cp -r misc/nsclient/src {{ nsclient_installfiles }}/

# {% trans "Put the ip address of the nagios server in here:" %}
vim {{ nsclient_installfiles }}/datafiles/allowed_hosts.ini
                </pre>
                {% trans "See more about this issue" %} <a href="https://github.com/opinkerfi/okconfig/wiki/Deploying-nsclient-on-windows-servers">{% trans "here" %}</a>.
        </div>
    </div>


    {% if stdout %}
        Script output: <pre id="stdout">{{ stdout }}</pre>
    {% endif %}

    {% if stderr %}
        Errors: <pre id="stderr">{{ stderr }}</pre>
    {% endif %}


    <!-- Ugly hack till we can pass css to bootstrap_fields -->
    <div id="install_agent" class="hide">
        <form action="#" method="post" class="form-horizontal">{% csrf_token %}
            {% include "bootstrap_fields.html" with fields=form %}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
            </div>
        </form>
    </div>

{% endblock %}

adagios/okconfig_/templates/okconfig_menubar.html
<!--
okconfig_menubar.html is responsible for creating the menuitems in top_navigation_bar of adagios
-->

{% load i18n %}

<li class="dropdown">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="#"><i class="glyph-edit glyph-grey"></i> {% trans "Okconfig" %} <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{% url "okconfig_.views.addhost" %}">{% trans "Add Host" %}</a></li>
        <li><a href="{% url "okconfig_.views.addtemplate" %}">{% trans "Add Template to Host" %}</a></li>
        <li><a href="{% url "okconfig_.views.addservice" %}">{% trans "Add Service" %}</a></li>
        <li><a href="{% url "okconfig_.views.choose_host" %}">{% trans "Edit Host" %}</a></li>
        <li><a href="{% url "okconfig_.views.addgroup" %}">{% trans "Add Group" %}</a></li>
        <li><a href="{% url "okconfig_.views.install_agent" %}">{% trans "Install Agent" %}</a></li>
        <li><a href="{% url "okconfig_.views.scan_network" %}">{% trans "Scan Network" %}</a></li>
    </ul>
</li>

adagios/okconfig_/templates/verify_okconfig.html
{% extends "base.html" %}
{% load i18n %}
{% load cycle from future %}

{% block title %}{% trans "Edit Host" %}{% endblock %}
{% block smallheader %}{% trans "Edit" %}{% endblock %}
{% block largeheader %}{% trans "Host" %}{% endblock %}
{% block toolbar %}{% endblock %}
{% block content %}
{% if okconfig_checks %}


<div>
	<table>
	 <thead><tr>
	  <th>{% trans "Check" %}</th>
	  <th>{% trans "Result" %}</th>
	 </tr></thead>
	 <tbody>
		{% for check,value in okconfig_checks.items %}
		<tr class="{% cycle "even" "odd" %}">
	  		<td>{{ check }}</td>
	  		<td>{{ value }}</td>
		</tr>
		{% endfor %}
	 </tbody></table>
</div>
{% endif %}


{% endblock %}